version: '3'
services:
  proxy:
    volumes:
      - ./proxy/prod/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - 80:80
      - 443:443
  node:
    build:
      context: ./back
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node build/index.js
  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    command: npm start
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - www-html:/var/www/html
    depends_on:
      - proxy
    command: certonly --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --staging -d geoconect.ru  -d www.geoconect.ru
volumes:
  certbot-etc:
  certbot-var:
  www-html:
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/sammy/node_project/views/
  #     o: bind
networks:
  geo_net:
    driver: bridge
