version: '3'
services:
  proxy:
    volumes:
      - ./proxy/dev/nginx.conf:/etc/nginx/nginx.conf
  node:
    build:
      context: ./back
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./back/src/:/app/src/
      - ./db/:/app/db/
    command: npm run dev
  nextjs:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./front/src/:/app/src/
      - ./front/public/:/app/public/
    command: npm run dev
