FROM node:14.17-alpine
WORKDIR /app/
COPY package.json ./
COPY next.config.js ./
COPY .sentryclirc ./
COPY sentry.client.config.js ./
COPY sentry.server.config.js ./
COPY sentry.properties ./

RUN npm install

EXPOSE 3500
CMD npm run dev
